// ════════════════════════════════════════════════════════════════
// EVENTS.JS — Calendrier Comité de la Somme 2026
// Source : Calendrier officiel 2ème version (01/02/2026)
// Types : champ | concours | gp | cdc | jeunes | veterans | regional | propagande
// ════════════════════════════════════════════════════════════════

const EVENTS = [

  // ══════════════════════════════
  // JANVIER
  // ══════════════════════════════
  {date:'2026-01-06',titre:'ASPTT Amiens — Triplette Qualificatif 60 ans',type:'veterans',lieu:'ASPTT Amiens',heure:'9h00',formation:'Triplette',obs:'Limité à 48 éq.'},
  {date:'2026-01-13',titre:'ASPTT Amiens — Triplette Qualificatif 60 ans',type:'veterans',lieu:'ASPTT Amiens',heure:'9h00',formation:'Triplette',obs:'Limité à 48 éq.'},
  {date:'2026-01-17',titre:'Concours Roye',type:'concours',lieu:'Roye',heure:'14h00',formation:'Triplette',obs:'½J — Limité à 32 éq.'},
  {date:'2026-01-20',titre:'ASPTT Amiens — Triplette Qualificatif 60 ans',type:'veterans',lieu:'ASPTT Amiens',heure:'9h00',formation:'Triplette',obs:'Limité à 48 éq.'},
  {date:'2026-01-27',titre:'ASPTT Amiens — Triplette Qualificatif 60 ans',type:'veterans',lieu:'ASPTT Amiens',heure:'9h00',formation:'Triplette',obs:'Limité à 48 éq.'},
  {date:'2026-01-31',titre:'Concours Abbeville',type:'concours',lieu:'Abbeville',heure:'14h00',formation:'Doublette',obs:'½J'},

  // ══════════════════════════════
  // FÉVRIER
  // ══════════════════════════════
  {date:'2026-02-03',titre:'ASPTT Amiens — Finale Qualificatifs 60 ans',type:'veterans',lieu:'ASPTT Amiens',heure:'9h00',formation:'Triplette',obs:'Finale'},
  {date:'2026-02-07',titre:'Concours Feuquières',type:'concours',lieu:'Feuquières (Boulodrome)',heure:'14h00',formation:'Doublette',obs:'½J — Limité à 48 éq.'},
  {date:'2026-02-10',titre:'Corbie — Vétérans Doublette',type:'veterans',lieu:'Corbie',heure:'14h00',formation:'Doublette',obs:'½J'},
  {date:'2026-02-14',titre:'Concours Abbeville',type:'concours',lieu:'Abbeville',heure:'14h00',formation:'Triplette Mixte',obs:'½J'},
  {date:'2026-02-14',titre:'Concours Saint-Ouen',type:'concours',lieu:'Saint-Ouen',heure:'14h00',formation:'Triplette',obs:'½J'},
  {date:'2026-02-15',titre:'Concours Bourdon',type:'concours',lieu:'Bourdon',heure:'14h00',formation:'Doublette',obs:'½J'},
  {date:'2026-02-15',titre:'Concours Feuquières',type:'concours',lieu:'Feuquières (Boulodrome)',heure:'14h00',formation:'Triplette',obs:'½J — Limité à 48 éq.'},
  {date:'2026-02-17',titre:'ASPTT Amiens — Vétérans Triplette',type:'veterans',lieu:'ASPTT Amiens',heure:'14h00',formation:'Triplette',obs:'½J'},
  {date:'2026-02-19',titre:'Feuquières/Friville — Triplette Qualificatif 60 ans',type:'veterans',lieu:'Boulodrome Feuquières',heure:'9h00',formation:'Triplette',obs:'Limité à 48 éq.'},
  {date:'2026-02-21',titre:'Concours Abbeville',type:'concours',lieu:'Abbeville',heure:'14h00',formation:'Doublette',obs:'½J'},
  {date:'2026-02-21',titre:'Concours Saint-Ouen',type:'concours',lieu:'Saint-Ouen',heure:'14h00',formation:'Doublette',obs:'½J'},
  {date:'2026-02-21',titre:'Concours Roye',type:'concours',lieu:'Roye',heure:'14h00',formation:'Triplette',obs:'½J — Limité à 32 éq.'},
  {date:'2026-02-22',titre:'Concours Feuquières',type:'concours',lieu:'Feuquières (Boulodrome)',heure:'14h00',formation:'Triplette Mixte',obs:'½J — Limité à 48 éq.'},
  {date:'2026-02-26',titre:'Feuquières/Friville — Triplette Qualificatif 60 ans',type:'veterans',lieu:'Boulodrome Feuquières',heure:'9h00',formation:'Triplette',obs:'Limité à 48 éq.'},
  {date:'2026-02-28',titre:'Concours Longpré',type:'concours',lieu:'Longpré',heure:'14h00',formation:'Doublette',obs:'½J'},
  {date:'2026-02-28',titre:'Concours Saint-Ouen',type:'concours',lieu:'Saint-Ouen',heure:'14h00',formation:'Triplette Mixte',obs:'½J'},

  // ══════════════════════════════
  // MARS
  // ══════════════════════════════
  {date:'2026-03-01',titre:'Concours ASPTT Amiens — Doublette Féminin',type:'concours',lieu:'ASPTT Amiens',heure:'14h00',formation:'Doublette Féminin',obs:'½J'},
  {date:'2026-03-01',titre:'Concours Feuquières',type:'concours',lieu:'Feuquières (Boulodrome)',heure:'14h00',formation:'Triplette',obs:'½J — Limité à 48 éq.'},
  {date:'2026-03-03',titre:'Boves — Vétérans Doublette',type:'veterans',lieu:'Boves',heure:'14h00',formation:'Doublette',obs:'½J'},
  {date:'2026-03-05',titre:'Feuquières/Friville — Triplette Qualificatif 60 ans',type:'veterans',lieu:'Boulodrome Feuquières',heure:'9h00',formation:'Triplette',obs:'Limité à 48 éq.'},
  {date:'2026-03-07',titre:'Concours Gamaches',type:'concours',lieu:'Gamaches',heure:'14h00',formation:'Doublette',obs:'½J'},
  {date:'2026-03-07',titre:'Concours ASPTT Amiens — Challenge André Dournel',type:'concours',lieu:'ASPTT Amiens',heure:'14h00',formation:'Triplette Mixte',obs:'½J — Challenge André DOURNEL'},
  {date:'2026-03-07',titre:'Coupe de France Jeu Provençal (2 tours)',type:'regional',lieu:'Fienvillers / St Léger-lès-Domart',heure:'9h00',formation:'Jeu Provençal',obs:'2 tours'},
  {date:'2026-03-08',titre:'Concours Bourdon',type:'concours',lieu:'Bourdon',heure:'14h00',formation:'Doublette Mixte',obs:'½J'},
  {date:'2026-03-08',titre:'Concours Feuquières',type:'concours',lieu:'Feuquières (Boulodrome)',heure:'14h00',formation:'Doublette Mixte',obs:'½J — Limité à 48 éq.'},
  {date:'2026-03-08',titre:'Coupe de France Jeu Provençal (suite)',type:'regional',lieu:'Fienvillers / St Léger-lès-Domart',heure:'9h00',formation:'Jeu Provençal'},
  {date:'2026-03-10',titre:'ASPTT Amiens — Vétérans Doublette',type:'veterans',lieu:'ASPTT Amiens',heure:'14h00',formation:'Doublette',obs:'½J'},
  {date:'2026-03-12',titre:'Feuquières/Friville — Triplette Qualificatif 60 ans',type:'veterans',lieu:'Boulodrome Feuquières',heure:'9h00',formation:'Triplette',obs:'Limité à 48 éq.'},
  {date:'2026-03-13',titre:'Friville — Doublette Mêlée Qualificatif 60 ans',type:'veterans',lieu:'Friville',heure:'14h00',formation:'Doublette Mêlée',obs:'½J Qualificatif'},
  {date:'2026-03-14',titre:'Concours Ault',type:'concours',lieu:'Ault',heure:'14h00',formation:'Doublette',obs:'½J'},
  {date:'2026-03-14',titre:'Concours Boves',type:'concours',lieu:'Boves',heure:'9h00',formation:'Doublette',obs:'Journée'},
  {date:'2026-03-14',titre:'Coupe de France + Coupe de la Somme',type:'regional',lieu:'Oisemont',heure:'9h30',formation:'',obs:'2 tours — Jet du but 9h30'},
  {date:'2026-03-15',titre:'Coupe de France + Coupe de la Somme (suite)',type:'regional',lieu:'Oisemont',heure:'9h00',formation:''},
  {date:'2026-03-15',titre:'Concours Feuquières',type:'concours',lieu:'Feuquières (Boulodrome)',heure:'14h00',formation:'Triplette',obs:'½J — Limité à 48 éq.'},
  {date:'2026-03-17',titre:'Corbie — Vétérans Doublette',type:'veterans',lieu:'Corbie',heure:'14h00',formation:'Doublette',obs:'½J'},
  {date:'2026-03-19',titre:'Feuquières/Friville — Triplette Finale 60 ans',type:'veterans',lieu:'Boulodrome Feuquières',heure:'9h00',formation:'Triplette',obs:'Finale — 24 éq.'},
  {date:'2026-03-20',titre:'Friville — Doublette Mêlée Qualificatif 60 ans',type:'veterans',lieu:'Friville',heure:'14h00',formation:'Doublette Mêlée',obs:'½J Qualificatif'},
  {date:'2026-03-21',titre:'CHPT DÉPRT — Triplette Promotion',type:'champ',lieu:'Flixecourt',heure:'10h00',formation:'Triplette Promotion',obs:'Inscriptions avant le 12/3'},
  {date:'2026-03-22',titre:'CHPT DÉPRT — Triplette Promotion (reprise)',type:'champ',lieu:'Flixecourt',heure:'9h00',formation:'Triplette Promotion'},
  {date:'2026-03-24',titre:'ASPTT Amiens — Vétérans Doublette',type:'veterans',lieu:'ASPTT Amiens',heure:'14h00',formation:'Doublette',obs:'½J'},
  {date:'2026-03-26',titre:'Feuquières — Triplette Qualificatif 60 ans',type:'veterans',lieu:'Boulodrome Feuquières',heure:'9h00',formation:'Triplette',obs:'Limité à 48 éq.'},
  {date:'2026-03-27',titre:'Friville — Doublette Mêlée Qualificatif 60 ans',type:'veterans',lieu:'Friville',heure:'14h00',formation:'Doublette Mêlée',obs:'½J Qualificatif'},
  {date:'2026-03-28',titre:'CHPT DÉPRT — TT Senior Masc. + Doublette Senior Fém.',type:'champ',lieu:'Flixecourt',heure:'10h00',formation:'TT / Doublette Fém.',obs:'Inscriptions avant le 19/3'},
  {date:'2026-03-29',titre:'CHPT DÉPRT — TT Senior Masc., Doub. Fém. + TT Jeunes',type:'champ',lieu:'Flixecourt',heure:'9h00',formation:'TT / Doublette / Jeunes'},
  {date:'2026-03-29',titre:'CHPT DÉPRT — Tête-à-Tête Jeunes (J/C/M/B)',type:'jeunes',lieu:'Flixecourt',heure:'9h30',formation:'TT Jeunes',obs:'Sur place'},
  {date:'2026-03-31',titre:'ASPTT Amiens — Vétérans Triplette',type:'veterans',lieu:'ASPTT Amiens',heure:'14h00',formation:'Triplette',obs:'½J'},

  // ══════════════════════════════
  // AVRIL
  // ══════════════════════════════
  {date:'2026-04-02',titre:'Feuquières — Triplette Qualificatif 60 ans',type:'veterans',lieu:'Boulodrome Feuquières',heure:'9h00',formation:'Triplette',obs:'Limité à 48 éq.'},
  {date:'2026-04-03',titre:'Friville — Doublette Mêlée Qualificatif 60 ans',type:'veterans',lieu:'Friville',heure:'14h00',formation:'Doublette Mêlée',obs:'½J Qualificatif'},
  {date:'2026-04-04',titre:'Concours Friville',type:'concours',lieu:'Friville',heure:'14h00',formation:'Triplette Mixte',obs:'½J'},
  {date:'2026-04-04',titre:'CHPT DÉPRT — Triplette Jeu Provençal',type:'champ',lieu:'Albert',heure:'8h00',formation:'Triplette JP',obs:'Inscriptions avant le 26/3 — Homogène (ouvert aux Juniors)'},
  {date:'2026-04-05',titre:'Concours Gamaches',type:'concours',lieu:'Gamaches',heure:'14h00',formation:'Doublette',obs:'½J'},
  {date:'2026-04-05',titre:'CHPT DÉPRT — Triplette JP (reprise)',type:'champ',lieu:'Albert',heure:'9h00',formation:'Triplette JP'},
  {date:'2026-04-06',titre:'Concours Fressenneville',type:'concours',lieu:'Fressenneville',heure:'14h00',formation:'Doublette',obs:'½J'},
  {date:'2026-04-06',titre:'CHPT DÉPRT — Triplette JP (reprise) Poules de 3',type:'champ',lieu:'Albert',heure:'9h00',formation:'Triplette JP',obs:'Poules de 3'},
  {date:'2026-04-07',titre:'Poix — Vétérans Doublette',type:'veterans',lieu:'Poix',heure:'14h00',formation:'Doublette',obs:'½J'},
  {date:'2026-04-09',titre:'Feuquières — Triplette Qualificatif 60 ans',type:'veterans',lieu:'Boulodrome Feuquières',heure:'9h00',formation:'Triplette',obs:'Limité à 48 éq.'},
  {date:'2026-04-10',titre:'Friville — Doublette Mêlée Qualificatif 60 ans',type:'veterans',lieu:'Friville',heure:'14h00',formation:'Doublette Mêlée',obs:'½J Qualificatif'},
  {date:'2026-04-11',titre:'CHPT DÉPRT — Triplette Senior Masc. et Fém.',type:'champ',lieu:'Feuquières',heure:'10h00',formation:'Triplette Senior',obs:'Inscriptions avant le 2/4'},
  {date:'2026-04-12',titre:'CHPT DÉPRT — Trip. Senior Masc., Fém. + Trip. Jeunes + Tir Précision Jr',type:'champ',lieu:'Feuquières',heure:'9h00',formation:'Triplette Senior / Jeunes'},
  {date:'2026-04-12',titre:'CHPT DÉPRT — Triplette Jeunes (J/C/M) + Tir Précision Junior',type:'jeunes',lieu:'Feuquières',heure:'9h30',formation:'Triplette / Tir Précision',obs:'Sur place'},
  {date:'2026-04-14',titre:'Béthencourt — Vétérans Triplette',type:'veterans',lieu:'Béthencourt',heure:'14h00',formation:'Triplette',obs:'½J'},
  {date:'2026-04-14',titre:'Boves — Vétérans Doublette',type:'veterans',lieu:'Boves',heure:'14h00',formation:'Doublette',obs:'½J'},
  {date:'2026-04-15',titre:'Feuquières — Triplette Qualificatif 60 ans',type:'veterans',lieu:'Boulodrome Feuquières',heure:'9h00',formation:'Triplette',obs:'Limité à 48 éq.'},
  {date:'2026-04-16',titre:'Gamaches — Vétérans Doublette',type:'veterans',lieu:'Gamaches',heure:'14h00',formation:'Doublette',obs:'½J'},
  {date:'2026-04-17',titre:'Friville — Doublette Mêlée Qualificatif 60 ans',type:'veterans',lieu:'Friville',heure:'14h00',formation:'Doublette Mêlée',obs:'½J Qualificatif'},
  {date:'2026-04-18',titre:'Concours Ault',type:'concours',lieu:'Ault',heure:'14h00',formation:'Triplette',obs:'½J'},
  {date:'2026-04-18',titre:'CHPT DÉPRT — Doublette Mixte + Stage Jeunes',type:'champ',lieu:'Fienvillers-Doullens (Doullens)',heure:'10h00',formation:'Doublette Mixte',obs:'Inscriptions avant le 9/4'},
  {date:'2026-04-18',titre:'Stage Départemental Jeunes',type:'jeunes',lieu:'Doullens',heure:'',formation:'',obs:'J/C/M'},
  {date:'2026-04-19',titre:'CHPT DÉPRT — Doublette Mixte (reprise)',type:'champ',lieu:'Fienvillers-Doullens (Doullens)',heure:'9h00',formation:'Doublette Mixte'},
  {date:'2026-04-22',titre:'CHPT DÉPRT — Triplette Vétéran (60 ans)',type:'champ',lieu:'ASPTT Amiens',heure:'10h00',formation:'Triplette Vétéran',obs:'Inscriptions avant le 9/4'},
  {date:'2026-04-23',titre:'CHPT DÉPRT — Triplette Vétéran (reprise)',type:'champ',lieu:'ASPTT Amiens',heure:'9h00',formation:'Triplette Vétéran'},
  {date:'2026-04-24',titre:'Friville — Doublette Mêlée Qualificatif 60 ans',type:'veterans',lieu:'Friville',heure:'14h00',formation:'Doublette Mêlée',obs:'½J Qualificatif'},
  {date:'2026-04-25',titre:'CHPT DÉPRT — Doublette Senior Masc. + TT Senior Fém.',type:'champ',lieu:'Feuquières',heure:'10h00',formation:'Doublette / TT',obs:'Inscriptions avant le 16/4'},
  {date:'2026-04-26',titre:'CHPT DÉPRT — Doub. Senior Masc., TT Fém. + Doublette Jeunes',type:'champ',lieu:'Feuquières',heure:'9h00',formation:'Doublette / TT / Jeunes'},
  {date:'2026-04-26',titre:'CHPT DÉPRT — Doublette Jeunes (J/C/M/B)',type:'jeunes',lieu:'Feuquières',heure:'9h30',formation:'Doublette Jeunes',obs:'Sur place'},
  {date:'2026-04-28',titre:'Corbie — Vétérans Doublette',type:'veterans',lieu:'Corbie',heure:'14h00',formation:'Doublette',obs:'½J'},
  {date:'2026-04-28',titre:'Feuquières — Finale Triplette 60 ans',type:'veterans',lieu:'Boulodrome Feuquières',heure:'9h00',formation:'Triplette',obs:'Finale'},
  {date:'2026-04-30',titre:'Feuquières — Triplette Qualificatif 60 ans',type:'veterans',lieu:'Boulodrome Feuquières',heure:'9h00',formation:'Triplette',obs:'Limité à 48 éq.'},

  // ══════════════════════════════
  // MAI
  // ══════════════════════════════
  {date:'2026-05-01',titre:'Concours Chépy',type:'concours',lieu:'Chépy',heure:'14h00',formation:'Doublette',obs:'½J'},
  {date:'2026-05-02',titre:'Concours Longpré',type:'concours',lieu:'Longpré',heure:'14h00',formation:'Doublette',obs:'½J'},
  {date:'2026-05-02',titre:'CHPT DÉPRT — Triplette Mixte',type:'champ',lieu:'Gamaches',heure:'10h00',formation:'Triplette Mixte',obs:'Inscriptions avant le 23/4'},
  {date:'2026-05-03',titre:'CHPT DÉPRT — Triplette Mixte (reprise)',type:'champ',lieu:'Gamaches',heure:'9h00',formation:'Triplette Mixte'},
  {date:'2026-05-05',titre:'Trophée Tête-à-Tête Vétéran (60 ans)',type:'veterans',lieu:'Feuquières',heure:'9h00',formation:'Tête-à-Tête',obs:'Sur place'},
  {date:'2026-05-07',titre:'Feuquières — Finale Triplette 60 ans',type:'veterans',lieu:'Boulodrome Feuquières',heure:'9h00',formation:'Triplette',obs:'Finale — 24 éq.'},
  {date:'2026-05-08',titre:'Concours Dargnies',type:'concours',lieu:'Dargnies',heure:'14h00',formation:'Doublette',obs:'½J'},
  {date:'2026-05-08',titre:'CHPT DÉPRT — Doublette Jeu Provençal',type:'champ',lieu:'Fienvillers / St Léger-lès-Domart',heure:'8h00',formation:'Doublette JP',obs:'Inscriptions avant le 31/4'},
  {date:'2026-05-09',titre:'Concours Feuquières',type:'concours',lieu:'Feuquières',heure:'14h00',formation:'Doublette',obs:'½J'},
  {date:'2026-05-09',titre:'Concours Boves',type:'concours',lieu:'Boves',heure:'14h00',formation:'Doublette Mixte',obs:'½J'},
  {date:'2026-05-09',titre:'CHPT DÉPRT — Doublette JP (reprise)',type:'champ',lieu:'St Léger-lès-Domart',heure:'9h00',formation:'Doublette JP'},
  {date:'2026-05-10',titre:'CHPT DÉPRT — Doublette JP (reprise) Poules de 3',type:'champ',lieu:'St Léger-lès-Domart',heure:'9h00',formation:'Doublette JP',obs:'Poules de 3'},
  {date:'2026-05-12',titre:'Friville — Vétérans Doublette',type:'veterans',lieu:'Friville',heure:'14h00',formation:'Doublette',obs:'½J'},
  {date:'2026-05-12',titre:'Poix — Vétérans Doublette',type:'veterans',lieu:'Poix',heure:'14h00',formation:'Doublette',obs:'½J'},
  {date:'2026-05-14',titre:'9ème Grand Prix de la Ville d\'Oisemont — Triplettes',type:'gp',lieu:'Oisemont',heure:'10h00',formation:'Triplette',obs:'18€/éq. — Limité à 80 trip. — Inscriptions par courrier avant le 8/5'},
  {date:'2026-05-14',titre:'CHPT RÉGIONAL Hauts-de-France — Triplette Masc. + Fém.',type:'regional',lieu:'Burbure (62)',heure:'9h00',formation:'Triplette'},
  {date:'2026-05-15',titre:'Grand Prix de Bourdon 60 ans — Triplette Vétéran',type:'gp',lieu:'Bourdon',heure:'9h30',formation:'Triplette Vétéran',obs:'15€/éq. + 500€ — Inscriptions par courrier'},
  {date:'2026-05-15',titre:'CHPT RÉGIONAL HdF — Triplette Jeunes + Tir Précision Junior',type:'regional',lieu:'Saint-Just-en-Chaussée (60)',heure:'9h30',formation:'Triplette / Tir Précision',obs:'J/C/M'},
  {date:'2026-05-15',titre:'Concours Oisemont',type:'concours',lieu:'Oisemont',heure:'14h00',formation:'Doublette Mixte',obs:'½J'},
  {date:'2026-05-16',titre:'6ème Grand Prix de Bourdon — Triplette',type:'gp',lieu:'Bourdon',heure:'9h30',formation:'Triplette',obs:'12€/éq. + 500€ — Inscriptions par courrier'},
  {date:'2026-05-16',titre:'CHPT RÉGIONAL HdF — Doublette Mixte',type:'regional',lieu:'Pernois (80)',heure:'9h00',formation:'Doublette Mixte'},
  {date:'2026-05-17',titre:'3ème Grand Prix de Bourdon — Triplette Mixte',type:'gp',lieu:'Bourdon',heure:'9h30',formation:'Triplette Mixte',obs:'12€/éq. + 500€ — Inscriptions par courrier'},
  {date:'2026-05-17',titre:'CHPT RÉGIONAL HdF — Triplette Mixte',type:'regional',lieu:'Pernois (80)',heure:'9h00',formation:'Triplette Mixte'},
  {date:'2026-05-19',titre:'Trophée Doublette Vétéran (60 ans)',type:'veterans',lieu:'Boves',heure:'9h00',formation:'Doublette',obs:'Sur place'},
  {date:'2026-05-22',titre:'Friville — Doublette Mêlée Qualificatif 60 ans',type:'veterans',lieu:'Friville',heure:'14h00',formation:'Doublette Mêlée',obs:'½J Qualificatif'},
  {date:'2026-05-23',titre:'Grand Prix de Péronne — Doublette',type:'gp',lieu:'Péronne (Parc des Expositions)',heure:'9h00',formation:'Doublette',obs:'Mises + 500€ — Par poules — Jet but 9h'},
  {date:'2026-05-23',titre:'CHPT RÉGIONAL HdF — Triplette Promotion',type:'regional',lieu:'Armentières (59)',heure:'9h00',formation:'Triplette Promotion'},
  {date:'2026-05-24',titre:'Concours Dargnies',type:'concours',lieu:'Dargnies',heure:'14h00',formation:'Doublette',obs:'½J'},
  {date:'2026-05-25',titre:'Concours Oisemont — Souvenir M. Gibergues',type:'concours',lieu:'Oisemont',heure:'10h00',formation:'Doublette',obs:'Journée — Jet but 10h'},
  {date:'2026-05-25',titre:'CHPT RÉGIONAL HdF — TT Masc. + Doublette Fém.',type:'regional',lieu:'Armentières (59)',heure:'9h00',formation:'TT / Doublette'},
  {date:'2026-05-26',titre:'ASPTT Amiens — Vétérans Doublette',type:'veterans',lieu:'ASPTT Amiens',heure:'14h00',formation:'Doublette',obs:'½J'},
  {date:'2026-05-27',titre:'Longpré — Vétérans Doublette',type:'veterans',lieu:'Longpré',heure:'14h00',formation:'Doublette',obs:'½J'},
  {date:'2026-05-29',titre:'Friville — Doublette Mêlée Finale Qualificatif 60 ans',type:'veterans',lieu:'Friville',heure:'14h00',formation:'Doublette Mêlée',obs:'½J Finale Qualificatif'},
  {date:'2026-05-29',titre:'Concours Ault',type:'concours',lieu:'Ault',heure:'19h00',formation:'Doublette',obs:'Soirée-Nocturne'},
  {date:'2026-05-30',titre:'Concours Feuquières',type:'concours',lieu:'Feuquières',heure:'14h00',formation:'Doublette',obs:'½J'},
  {date:'2026-05-30',titre:'Concours ASPTT Amiens',type:'concours',lieu:'ASPTT Amiens',heure:'14h00',formation:'Doublette',obs:'½J'},

  // ══════════════════════════════
  // JUIN
  // ══════════════════════════════
  {date:'2026-06-02',titre:'Trophée Triplette Mixte Vétéran (60 ans)',type:'veterans',lieu:'Béthencourt',heure:'9h00',formation:'Triplette Mixte',obs:'Sur place'},
  {date:'2026-06-03',titre:'Friville — Vétérans Doublette',type:'veterans',lieu:'Friville',heure:'14h00',formation:'Doublette',obs:'½J'},
  {date:'2026-06-06',titre:'Grand Prix d\'Abbeville — Triplette',type:'gp',lieu:'Abbeville',heure:'14h00',formation:'Triplette',obs:'15€/éq. — Limité 72 éq. — Mises + 500€ — Inscriptions par courrier'},
  {date:'2026-06-09',titre:'Poix — Vétérans Doublette',type:'veterans',lieu:'Poix',heure:'14h00',formation:'Doublette',obs:'½J'},
  {date:'2026-06-11',titre:'Gamaches — Vétérans Doublette',type:'veterans',lieu:'Gamaches',heure:'14h00',formation:'Doublette',obs:'½J'},
  {date:'2026-06-06',titre:'CHPT RÉGIONAL HdF — Doublette Jeu Provençal',type:'regional',lieu:'Gauchy (02)',heure:'9h00',formation:'Doublette JP'},
  {date:'2026-06-07',titre:'CHPT RÉGIONAL HdF — Doublette Jeu Provençal (suite)',type:'regional',lieu:'Gauchy (02)',heure:'9h00',formation:'Doublette JP'},
  {date:'2026-06-13',titre:'Concours Dargnies',type:'concours',lieu:'Dargnies',heure:'14h00',formation:'Doublette',obs:'½J'},
  {date:'2026-06-13',titre:'Concours Péronne',type:'concours',lieu:'Péronne',heure:'14h00',formation:'Doublette',obs:'½J'},
  {date:'2026-06-16',titre:'ASPTT Amiens — Vétérans Doublette',type:'veterans',lieu:'ASPTT Amiens',heure:'14h00',formation:'Doublette',obs:'½J'},
  {date:'2026-06-18',titre:'Roye — Vétérans Doublette',type:'veterans',lieu:'Roye',heure:'14h00',formation:'Doublette',obs:'½J'},
  {date:'2026-06-19',titre:'Concours Friville',type:'concours',lieu:'Friville',heure:'19h00',formation:'Triplette',obs:'Soirée-Nocturne'},
  {date:'2026-06-19',titre:'Boves — Vétérans Triplette',type:'veterans',lieu:'Boves',heure:'9h00',formation:'Triplette',obs:'Journée'},
  {date:'2026-06-20',titre:'Concours Bouvaincourt',type:'concours',lieu:'Bouvaincourt',heure:'14h00',formation:'Doublette',obs:'½J'},
  {date:'2026-06-20',titre:'Concours Boves',type:'concours',lieu:'Boves',heure:'9h00',formation:'Triplette',obs:'Journée'},
  {date:'2026-06-20',titre:'Concours Roye',type:'concours',lieu:'Roye',heure:'14h00',formation:'Doublette',obs:'½J'},
  {date:'2026-06-20',titre:'CHPT DE FRANCE — Triplette Masc. et Fém.',type:'regional',lieu:'Sin-le-Noble (59)',heure:'',formation:'Triplette'},
  {date:'2026-06-21',titre:'Concours Béthencourt',type:'concours',lieu:'Béthencourt',heure:'14h00',formation:'Doublette',obs:'½J'},
  {date:'2026-06-23',titre:'Corbie — Vétérans Doublette',type:'veterans',lieu:'Corbie',heure:'14h00',formation:'Doublette',obs:'½J'},
  {date:'2026-06-24',titre:'Longpré — Vétérans Doublette',type:'veterans',lieu:'Longpré',heure:'14h00',formation:'Doublette',obs:'½J'},
  {date:'2026-06-26',titre:'Mers — Vétérans Doublette',type:'veterans',lieu:'Mers-les-Bains',heure:'14h00',formation:'Doublette',obs:'½J'},
  {date:'2026-06-26',titre:'Pernois — Vétérans Triplette Challenge',type:'veterans',lieu:'Pernois',heure:'9h00',formation:'Triplette',obs:'Journée — Challenge'},
  {date:'2026-06-27',titre:'Concours Feuquières',type:'concours',lieu:'Feuquières',heure:'14h00',formation:'Doublette',obs:'½J'},
  {date:'2026-06-27',titre:'Concours Pernois — Triplette Challenge',type:'concours',lieu:'Pernois',heure:'9h00',formation:'Triplette',obs:'Journée — Challenge'},
  {date:'2026-06-27',titre:'CHPT DE FRANCE — Doublette Mixte',type:'regional',lieu:'Ajaccio (2A)',heure:'',formation:'Doublette Mixte'},
  {date:'2026-06-28',titre:'Concours Ault',type:'concours',lieu:'Ault',heure:'14h00',formation:'Triplette Mixte',obs:'½J'},
  {date:'2026-06-28',titre:'Concours Bourdon',type:'concours',lieu:'Bourdon',heure:'14h00',formation:'Doublette',obs:'½J'},
  {date:'2026-06-30',titre:'ASPTT Amiens — Vétérans Doublette',type:'veterans',lieu:'ASPTT Amiens',heure:'14h00',formation:'Doublette',obs:'½J'},

  // ══════════════════════════════
  // JUILLET — PROPAGANDES & GP
  // ══════════════════════════════
  {date:'2026-07-01',titre:'Concours Mers-les-Bains — Propagande',type:'propagande',lieu:'Mers-les-Bains',heure:'14h00',formation:'Doublette',obs:'½J — 4 parties'},
  {date:'2026-07-01',titre:'Concours Ham — Propagande',type:'propagande',lieu:'Ham',heure:'14h30',formation:'Doublette',obs:'Propagande'},
  {date:'2026-07-02',titre:'Concours Gamaches — Propagande',type:'propagande',lieu:'Gamaches',heure:'14h00',formation:'Doublette',obs:'½J — 4 parties'},
  {date:'2026-07-03',titre:'Concours Feuquières — Propagande',type:'propagande',lieu:'Feuquières',heure:'14h00',formation:'Doublette',obs:'½J — 4 parties'},
  {date:'2026-07-03',titre:'CHPT DE FRANCE — Triplette Jeu Provençal',type:'regional',lieu:'Blaye-les-Mines (81)',heure:'',formation:'Triplette JP'},
  {date:'2026-07-04',titre:'Concours Mers — Triplette Propagande Challenge',type:'propagande',lieu:'Mers-les-Bains',heure:'9h00',formation:'Triplette',obs:'Journée — Challenge'},
  {date:'2026-07-04',titre:'Concours Saint-Ouen — Propagande',type:'propagande',lieu:'Saint-Ouen',heure:'19h00',formation:'Doublette',obs:'Soirée-Nocturne'},
  {date:'2026-07-04',titre:'Concours Roye — Propagande',type:'propagande',lieu:'Roye',heure:'14h00',formation:'Doublette',obs:'½J — Propagande'},
  {date:'2026-07-05',titre:'Concours Oisemont — Propagande',type:'propagande',lieu:'Oisemont',heure:'14h00',formation:'Doublette',obs:'½J — Propagande'},
  {date:'2026-07-05',titre:'Concours Boves — Propagande',type:'propagande',lieu:'Boves',heure:'14h00',formation:'Triplette',obs:'½J — 4 parties'},
  {date:'2026-07-06',titre:'Concours Mers — Propagande',type:'propagande',lieu:'Mers-les-Bains',heure:'14h00',formation:'Doublette',obs:'½J — 4 parties'},
  {date:'2026-07-07',titre:'Béthencourt — Vétérans Doublette',type:'veterans',lieu:'Béthencourt',heure:'14h00',formation:'Doublette',obs:'½J — Propagande'},
  {date:'2026-07-07',titre:'Boves — Vétérans Doublette',type:'veterans',lieu:'Boves',heure:'14h00',formation:'Doublette',obs:'½J'},
  {date:'2026-07-08',titre:'Concours Mers — Propagande',type:'propagande',lieu:'Mers-les-Bains',heure:'14h00',formation:'Doublette',obs:'½J — 4 parties'},
  {date:'2026-07-08',titre:'Concours Ham — Propagande',type:'propagande',lieu:'Ham',heure:'14h30',formation:'Doublette',obs:'Propagande'},
  {date:'2026-07-09',titre:'Concours Gamaches — Propagande',type:'propagande',lieu:'Gamaches',heure:'14h00',formation:'Doublette',obs:'½J — 4 parties'},
  {date:'2026-07-10',titre:'Concours Feuquières — Propagande',type:'propagande',lieu:'Feuquières',heure:'14h00',formation:'Doublette',obs:'½J — 4 parties'},
  {date:'2026-07-11',titre:'Grand Prix de Bouvaincourt — Triplette',type:'gp',lieu:'Bouvaincourt',heure:'9h30',formation:'Triplette',obs:'Mises + 500€ — Limité 64 éq. — Inscriptions par courrier'},
  {date:'2026-07-11',titre:'CHPT DE FRANCE — Triplette Jeunes',type:'regional',lieu:'Blaye-les-Mines (81)',heure:'',formation:'Triplette Jeunes',obs:'J/C/M'},
  {date:'2026-07-12',titre:'Concours Ault — Propagande',type:'propagande',lieu:'Ault',heure:'14h00',formation:'Doublette',obs:'½J'},
  {date:'2026-07-12',titre:'Concours Fienvillers-Doullens — Propagande',type:'propagande',lieu:'Doullens',heure:'14h00',formation:'Triplette',obs:'½J'},
  {date:'2026-07-13',titre:'Concours Mers — Propagande',type:'propagande',lieu:'Mers-les-Bains',heure:'14h00',formation:'Doublette',obs:'½J — 4 parties'},
  {date:'2026-07-14',titre:'Grand Prix de Gamaches — Triplette',type:'gp',lieu:'Gamaches',heure:'9h00',formation:'Triplette',obs:'15€/éq. + 500€ — Limité 80 trip. — Inscriptions avant le 30 juin'},
  {date:'2026-07-15',titre:'Concours Mers — Propagande',type:'propagande',lieu:'Mers-les-Bains',heure:'14h00',formation:'Doublette',obs:'½J — 4 parties'},
  {date:'2026-07-16',titre:'Concours Ham — Propagande',type:'propagande',lieu:'Ham',heure:'14h30',formation:'Doublette',obs:'Propagande'},
  {date:'2026-07-16',titre:'Concours Gamaches — Propagande',type:'propagande',lieu:'Gamaches',heure:'14h00',formation:'Doublette',obs:'½J — 4 parties'},
  {date:'2026-07-17',titre:'Ham — Vétérans Doublette Propagande',type:'veterans',lieu:'Ham',heure:'14h00',formation:'Doublette',obs:'½J — Propagande'},
  {date:'2026-07-17',titre:'Concours Feuquières — Propagande',type:'propagande',lieu:'Feuquières',heure:'14h00',formation:'Doublette',obs:'½J — 4 parties'},
  {date:'2026-07-18',titre:'Concours Fressenneville — Propagande',type:'propagande',lieu:'Fressenneville',heure:'14h00',formation:'Doublette',obs:'½J — 4 parties'},
  {date:'2026-07-18',titre:'Concours Dreuil — Propagande',type:'propagande',lieu:'Dreuil',heure:'14h00',formation:'Doublette',obs:'½J — 4 parties'},
  {date:'2026-07-18',titre:'CHPT DÉPRT — Clubs Jeu Provençal (J1)',type:'cdc',lieu:'Nesle et …',heure:'',formation:'Jeu Provençal'},
  {date:'2026-07-18',titre:'CHPT DE FRANCE — Triplette Mixte',type:'regional',lieu:'Nice (06)',heure:'',formation:'Triplette Mixte'},
  {date:'2026-07-19',titre:'CHPT DÉPRT — Clubs Jeu Provençal (J2)',type:'cdc',lieu:'Nesle et …',heure:'',formation:'Jeu Provençal'},
  {date:'2026-07-20',titre:'Concours Mers — Propagande',type:'propagande',lieu:'Mers-les-Bains',heure:'14h00',formation:'Doublette',obs:'½J — 4 parties'},
  {date:'2026-07-21',titre:'Concours Friville — Propagande',type:'propagande',lieu:'Friville',heure:'14h00',formation:'Doublette',obs:'½J — 4 parties'},
  {date:'2026-07-21',titre:'ASPTT Amiens — Vétérans Doublette',type:'veterans',lieu:'ASPTT Amiens',heure:'14h00',formation:'Doublette',obs:'½J'},
  {date:'2026-07-22',titre:'Concours Mers — Propagande',type:'propagande',lieu:'Mers-les-Bains',heure:'14h00',formation:'Doublette',obs:'½J — 4 parties'},
  {date:'2026-07-22',titre:'Concours Ham — Propagande',type:'propagande',lieu:'Ham',heure:'14h30',formation:'Doublette',obs:'Propagande'},
  {date:'2026-07-23',titre:'Concours Gamaches — Propagande',type:'propagande',lieu:'Gamaches',heure:'14h00',formation:'Doublette',obs:'½J — 4 parties'},
  {date:'2026-07-24',titre:'Concours Béthencourt — Propagande Soirée-Nocturne',type:'propagande',lieu:'Béthencourt',heure:'19h00',formation:'Doublette',obs:'Soirée-Nocturne — Propagande'},
  {date:'2026-07-24',titre:'Ham — Vétérans Doublette Propagande',type:'veterans',lieu:'Ham',heure:'14h00',formation:'Doublette',obs:'½J — Propagande'},
  {date:'2026-07-24',titre:'Concours Feuquières — Propagande',type:'propagande',lieu:'Feuquières',heure:'14h00',formation:'Doublette',obs:'½J — 4 parties'},
  {date:'2026-07-25',titre:'Concours Longpré — Propagande',type:'propagande',lieu:'Longpré',heure:'14h00',formation:'Doublette',obs:'½J — Propagande'},
  {date:'2026-07-25',titre:'Concours ASPTT Amiens',type:'concours',lieu:'ASPTT Amiens',heure:'14h00',formation:'Doublette',obs:'½J'},
  {date:'2026-07-25',titre:'CHPT DE FRANCE — TT Masc. + Doublette Fém.',type:'regional',lieu:'Bergerac (24)',heure:'',formation:'TT / Doublette'},
  {date:'2026-07-26',titre:'Concours Fressenneville — Propagande',type:'propagande',lieu:'Fressenneville',heure:'14h00',formation:'Doublette',obs:'½J — 4 parties'},
  {date:'2026-07-26',titre:'Concours Bourdon',type:'concours',lieu:'Bourdon',heure:'14h00',formation:'Doublette',obs:'½J'},
  {date:'2026-07-27',titre:'Concours Mers — Propagande',type:'propagande',lieu:'Mers-les-Bains',heure:'14h00',formation:'Doublette',obs:'½J — 4 parties'},
  {date:'2026-07-28',titre:'Concours Friville — Propagande',type:'propagande',lieu:'Friville',heure:'14h00',formation:'Doublette',obs:'½J — 4 parties'},
  {date:'2026-07-29',titre:'Concours Mers — Propagande',type:'propagande',lieu:'Mers-les-Bains',heure:'14h00',formation:'Doublette',obs:'½J — 4 parties'},
  {date:'2026-07-29',titre:'Concours Ham — Propagande',type:'propagande',lieu:'Ham',heure:'14h30',formation:'Doublette',obs:'Propagande'},
  {date:'2026-07-30',titre:'Concours Gamaches — Propagande',type:'propagande',lieu:'Gamaches',heure:'14h00',formation:'Doublette',obs:'½J — 4 parties'},
  {date:'2026-07-31',titre:'Ham — Vétérans Doublette Propagande',type:'veterans',lieu:'Ham',heure:'14h00',formation:'Doublette',obs:'½J — Propagande'},
  {date:'2026-07-31',titre:'Concours Feuquières — Propagande',type:'propagande',lieu:'Feuquières',heure:'14h00',formation:'Doublette',obs:'½J — 4 parties'},

  // ══════════════════════════════
  // AOÛT — PROPAGANDES
  // ══════════════════════════════
  {date:'2026-08-01',titre:'Concours Chépy — Propagande',type:'propagande',lieu:'Chépy',heure:'14h00',formation:'Doublette',obs:'½J — Propagande'},
  {date:'2026-08-01',titre:'Concours Pernois — Propagande',type:'propagande',lieu:'Pernois',heure:'14h00',formation:'Doublette',obs:'½J — 4 parties'},
  {date:'2026-08-02',titre:'Concours Ault — Propagande',type:'propagande',lieu:'Ault',heure:'14h00',formation:'Triplette',obs:'½J — Propagande'},
  {date:'2026-08-02',titre:'Concours Roye — Propagande',type:'propagande',lieu:'Roye',heure:'14h00',formation:'Doublette',obs:'½J — Propagande'},
  {date:'2026-08-03',titre:'Concours Mers — Propagande',type:'propagande',lieu:'Mers-les-Bains',heure:'14h00',formation:'Doublette',obs:'½J — 4 parties'},
  {date:'2026-08-04',titre:'Concours Friville — Propagande',type:'propagande',lieu:'Friville',heure:'14h00',formation:'Doublette',obs:'½J — 4 parties'},
  {date:'2026-08-04',titre:'ASPTT Amiens — Vétérans Doublette',type:'veterans',lieu:'ASPTT Amiens',heure:'14h00',formation:'Doublette',obs:'½J'},
  {date:'2026-08-05',titre:'Concours Mers — Propagande',type:'propagande',lieu:'Mers-les-Bains',heure:'14h00',formation:'Doublette',obs:'½J — 4 parties'},
  {date:'2026-08-05',titre:'Concours Ham — Propagande',type:'propagande',lieu:'Ham',heure:'14h30',formation:'Doublette',obs:'Propagande'},
  {date:'2026-08-06',titre:'Concours Gamaches — Propagande',type:'propagande',lieu:'Gamaches',heure:'14h00',formation:'Doublette',obs:'½J — 4 parties'},
  {date:'2026-08-07',titre:'Concours Feuquières — Propagande',type:'propagande',lieu:'Feuquières',heure:'14h00',formation:'Doublette',obs:'½J — 4 parties'},
  {date:'2026-08-08',titre:'Concours Abbeville — Propagande',type:'propagande',lieu:'Abbeville',heure:'14h00',formation:'Doublette',obs:'½J — Propagande'},
  {date:'2026-08-08',titre:'Concours Boves — Propagande',type:'propagande',lieu:'Boves',heure:'14h00',formation:'Doublette',obs:'½J — 4 parties'},
  {date:'2026-08-09',titre:'Concours Dargnies — Propagande',type:'propagande',lieu:'Dargnies',heure:'14h00',formation:'Doublette',obs:'½J — Propagande'},
  {date:'2026-08-10',titre:'Concours Mers — Propagande',type:'propagande',lieu:'Mers-les-Bains',heure:'14h00',formation:'Doublette',obs:'½J — 4 parties'},
  {date:'2026-08-11',titre:'Concours Friville — Propagande',type:'propagande',lieu:'Friville',heure:'14h00',formation:'Doublette',obs:'½J — 4 parties'},
  {date:'2026-08-12',titre:'Concours Mers — Propagande',type:'propagande',lieu:'Mers-les-Bains',heure:'14h00',formation:'Doublette',obs:'½J — 4 parties'},
  {date:'2026-08-12',titre:'Concours Ham — Propagande',type:'propagande',lieu:'Ham',heure:'14h30',formation:'Doublette',obs:'Propagande'},
  {date:'2026-08-13',titre:'Concours Gamaches — Propagande',type:'propagande',lieu:'Gamaches',heure:'14h00',formation:'Doublette',obs:'½J — 4 parties'},
  {date:'2026-08-14',titre:'Concours Feuquières — Propagande Journée',type:'propagande',lieu:'Feuquières',heure:'9h00',formation:'Doublette',obs:'Journée — Propagande'},
  {date:'2026-08-15',titre:'Concours Bouvaincourt — Propagande',type:'propagande',lieu:'Bouvaincourt',heure:'14h00',formation:'Doublette',obs:'½J — Propagande'},
  {date:'2026-08-16',titre:'Concours Fressenneville — Propagande',type:'propagande',lieu:'Fressenneville',heure:'14h00',formation:'Doublette',obs:'½J — 4 parties'},
  {date:'2026-08-17',titre:'Concours Mers — Propagande',type:'propagande',lieu:'Mers-les-Bains',heure:'14h00',formation:'Doublette',obs:'½J — 4 parties'},
  {date:'2026-08-18',titre:'Concours Béthencourt — Propagande',type:'propagande',lieu:'Béthencourt',heure:'14h00',formation:'Doublette',obs:'½J — 4 parties'},
  {date:'2026-08-19',titre:'Concours Mers — Propagande',type:'propagande',lieu:'Mers-les-Bains',heure:'14h00',formation:'Doublette',obs:'½J — 4 parties'},
  {date:'2026-08-19',titre:'Concours Ham — Propagande',type:'propagande',lieu:'Ham',heure:'14h30',formation:'Doublette',obs:'Propagande'},
  {date:'2026-08-19',titre:'CHPT DE FRANCE — Triplette Vétéran',type:'regional',lieu:'Saint-Yrieix (16)',heure:'',formation:'Triplette Vétéran'},
  {date:'2026-08-20',titre:'Concours Gamaches — Propagande',type:'propagande',lieu:'Gamaches',heure:'14h00',formation:'Doublette',obs:'½J — 4 parties'},
  {date:'2026-08-21',titre:'Péronne — Vétérans Doublette Propagande',type:'veterans',lieu:'Péronne',heure:'14h00',formation:'Doublette',obs:'½J — Propagande'},
  {date:'2026-08-21',titre:'Concours Feuquières — Propagande',type:'propagande',lieu:'Feuquières',heure:'14h00',formation:'Doublette',obs:'½J — 4 parties'},
  {date:'2026-08-22',titre:'Concours Oisemont — Propagande',type:'propagande',lieu:'Oisemont',heure:'14h00',formation:'Doublette',obs:'½J — Propagande'},
  {date:'2026-08-22',titre:'Concours Pernois — Propagande',type:'propagande',lieu:'Pernois',heure:'14h00',formation:'Doublette',obs:'½J — 4 parties'},
  {date:'2026-08-22',titre:'Concours Péronne — Propagande',type:'propagande',lieu:'Péronne',heure:'14h00',formation:'Doublette',obs:'½J — Propagande'},
  {date:'2026-08-22',titre:'CHPT DE FRANCE — Triplette Promotion',type:'regional',lieu:'Saint-Yrieix (16)',heure:'',formation:'Triplette Promotion'},
  {date:'2026-08-23',titre:'Concours Béthencourt — Propagande',type:'propagande',lieu:'Béthencourt',heure:'14h00',formation:'Doublette',obs:'½J — Propagande'},
  {date:'2026-08-23',titre:'Concours Saint-Ouen — Propagande',type:'propagande',lieu:'Saint-Ouen',heure:'14h00',formation:'Doublette',obs:'½J — 4 parties'},
  {date:'2026-08-23',titre:'Concours Roye — Propagande',type:'propagande',lieu:'Roye',heure:'14h00',formation:'Doublette',obs:'½J — Propagande'},
  {date:'2026-08-24',titre:'Concours Mers — Propagande',type:'propagande',lieu:'Mers-les-Bains',heure:'14h00',formation:'Doublette',obs:'½J — 4 parties'},
  {date:'2026-08-25',titre:'Concours Friville — Propagande',type:'propagande',lieu:'Friville',heure:'14h00',formation:'Doublette',obs:'½J — 4 parties'},
  {date:'2026-08-25',titre:'ASPTT Amiens — Vétérans Doublette',type:'veterans',lieu:'ASPTT Amiens',heure:'14h00',formation:'Doublette',obs:'½J'},
  {date:'2026-08-26',titre:'Concours Mers — Propagande',type:'propagande',lieu:'Mers-les-Bains',heure:'14h00',formation:'Doublette',obs:'½J — 4 parties'},
  {date:'2026-08-26',titre:'Concours Ham — Propagande',type:'propagande',lieu:'Ham',heure:'14h30',formation:'Doublette',obs:'Propagande'},
  {date:'2026-08-27',titre:'Concours Gamaches — Propagande',type:'propagande',lieu:'Gamaches',heure:'14h00',formation:'Doublette',obs:'½J — 4 parties'},
  {date:'2026-08-28',titre:'Concours Feuquières — Propagande',type:'propagande',lieu:'Feuquières',heure:'14h00',formation:'Doublette',obs:'½J — 4 parties'},
  {date:'2026-08-29',titre:'Concours Mers — Triplette Mixte Propagande',type:'propagande',lieu:'Mers-les-Bains',heure:'14h00',formation:'Triplette Mixte',obs:'½J — Propagande'},
  {date:'2026-08-29',titre:'Concours Dreuil — Propagande',type:'propagande',lieu:'Dreuil',heure:'14h00',formation:'Doublette',obs:'½J — 4 parties'},
  {date:'2026-08-29',titre:'CHPT DE FRANCE — Doublette Masc. + TT Fém.',type:'regional',lieu:'Saint-Florentin (89)',heure:'',formation:'Doublette / TT'},
  {date:'2026-08-30',titre:'Concours Bouvaincourt — Propagande',type:'propagande',lieu:'Bouvaincourt',heure:'14h00',formation:'Doublette',obs:'½J — Propagande'},
  {date:'2026-08-31',titre:'Concours Mers — Propagande',type:'propagande',lieu:'Mers-les-Bains',heure:'14h00',formation:'Doublette',obs:'½J — 4 parties'},

  // ══════════════════════════════
  // SEPTEMBRE
  // ══════════════════════════════
  {date:'2026-09-01',titre:'CDC Vétéran — 1ère Journée',type:'veterans',lieu:'Nesle et Béthencourt',heure:'',formation:'Championnat des Clubs'},
  {date:'2026-09-04',titre:'CHPT DE FRANCE — Doublette Jeu Provençal',type:'regional',lieu:'Briançon (05)',heure:'',formation:'Doublette JP'},
  {date:'2026-09-04',titre:'Mers — Vétérans Doublette',type:'veterans',lieu:'Mers-les-Bains',heure:'14h00',formation:'Doublette',obs:'½J'},
  {date:'2026-09-05',titre:'NATIONAL JEUNES — Triplette (1er jour)',type:'jeunes',lieu:'Montdidier',heure:'',formation:'Triplette J/C/M'},
  {date:'2026-09-05',titre:'CHPT DÉPRT — Clubs (J1)',type:'cdc',lieu:'Poix / Bouvaincourt',heure:'',formation:'Championnat des Clubs'},
  {date:'2026-09-06',titre:'NATIONAL JEUNES — Triplette (2ème jour) + Détection départementale',type:'jeunes',lieu:'Montdidier',heure:'',formation:'Triplette J/C/M'},
  {date:'2026-09-06',titre:'Concours Boves',type:'concours',lieu:'Boves',heure:'14h00',formation:'Doublette',obs:'½J'},
  {date:'2026-09-06',titre:'CHPT DÉPRT — Clubs Jeu Provençal (suite)',type:'cdc',lieu:'…',heure:'',formation:'Jeu Provençal'},
  {date:'2026-09-08',titre:'CDC Vétéran — 2ème Journée',type:'veterans',lieu:'Roye et Friville',heure:'',formation:'Championnat des Clubs'},
  {date:'2026-09-10',titre:'Feuquières — Vétérans Doublette',type:'veterans',lieu:'Feuquières (Boulodrome)',heure:'14h00',formation:'Doublette',obs:'Limité à 48 éq.'},
  {date:'2026-09-12',titre:'14ème Grand Prix de Friville — Triplette',type:'gp',lieu:'Friville',heure:'9h15',formation:'Triplette',obs:'12€/éq. + 500€ — Inscriptions par courrier avant le 8/9'},
  {date:'2026-09-13',titre:'Concours Fienvillers-Doullens',type:'concours',lieu:'Doullens',heure:'9h00',formation:'Doublette',obs:'Journée'},
  {date:'2026-09-15',titre:'CDC Vétéran — 3ème Journée',type:'veterans',lieu:'ASPTT Amiens et Friville',heure:'',formation:'Championnat des Clubs'},
  {date:'2026-09-16',titre:'Feuquières — Vétérans Triplette',type:'veterans',lieu:'Feuquières (Boulodrome)',heure:'14h00',formation:'Triplette',obs:'½J'},
  {date:'2026-09-17',titre:'Gamaches — Vétérans Doublette',type:'veterans',lieu:'Gamaches',heure:'14h00',formation:'Doublette',obs:'½J'},
  {date:'2026-09-19',titre:'Grand Prix de la Ville d\'Albert — Doublette',type:'gp',lieu:'Albert (Esplanade du Solidaire)',heure:'14h00',formation:'Doublette',obs:'10€/éq. + 500€ — Inscriptions sur place avant 13h45'},
  {date:'2026-09-20',titre:'CHPT DÉPRT — Clubs Jeu Provençal (Nesle)',type:'cdc',lieu:'Nesle',heure:'',formation:'Jeu Provençal'},
  {date:'2026-09-22',titre:'Finale CDC Vétéran',type:'veterans',lieu:'Béthencourt',heure:'',formation:'Finale'},
  {date:'2026-09-23',titre:'Feuquières — Vétérans Doublette',type:'veterans',lieu:'Feuquières (Boulodrome)',heure:'14h00',formation:'Doublette',obs:'½J'},
  {date:'2026-09-24',titre:'Ault — Vétérans Doublette Mêlée Qualificatif',type:'veterans',lieu:'Ault',heure:'14h00',formation:'Doublette Mêlée',obs:'½J Qualificatif'},
  {date:'2026-09-25',titre:'Grand Prix ASPTT Amiens 60 ans — Doublette',type:'gp',lieu:'ASPTT Amiens',heure:'',formation:'Doublette 60 ans',obs:'10€/éq. + 1000€ — Limité 128 éq. — Inscriptions en ligne asptt.com'},
  {date:'2026-09-26',titre:'Grand Prix Régional d\'Amiens — Triplette Mixte',type:'gp',lieu:'ASPTT Amiens',heure:'',formation:'Triplette Mixte',obs:'15€/éq. + 2000€ — Limité 128 éq. — Inscriptions en ligne asptt.com'},
  {date:'2026-09-27',titre:'Grand Prix de l\'ASPTT Amiens — Doublette',type:'gp',lieu:'ASPTT Amiens',heure:'',formation:'Doublette',obs:'10€/éq. + 1000€ — Limité 128 éq. — Inscriptions en ligne asptt.com'},

  // ══════════════════════════════
  // OCTOBRE
  // ══════════════════════════════
  {date:'2026-10-02',titre:'Ault — Vétérans Doublette Mêlée Qualificatif',type:'veterans',lieu:'Ault',heure:'14h00',formation:'Doublette Mêlée',obs:'½J Qualificatif'},
  {date:'2026-10-03',titre:'CHPT DÉPRT — Clubs Open et Féminin (J1)',type:'cdc',lieu:'Feuquières et Dreuil',heure:'',formation:'Open / Féminin'},
  {date:'2026-10-06',titre:'Boves — Vétérans Doublette',type:'veterans',lieu:'Boves',heure:'14h00',formation:'Doublette',obs:'½J'},
  {date:'2026-10-08',titre:'Feuquières — Vétérans Triplette Qualificatif',type:'veterans',lieu:'Feuquières (Boulodrome)',heure:'9h00',formation:'Triplette',obs:'Limité à 48 éq.'},
  {date:'2026-10-09',titre:'Ault — Vétérans Doublette Mêlée Qualificatif',type:'veterans',lieu:'Ault',heure:'14h00',formation:'Doublette Mêlée',obs:'½J Qualificatif'},
  {date:'2026-10-10',titre:'Concours Abbeville — Triplette Qualificatif',type:'concours',lieu:'Abbeville',heure:'9h00',formation:'Triplette',obs:'Journée — Jet but 9h'},
  {date:'2026-10-13',titre:'Corbie — Vétérans Doublette',type:'veterans',lieu:'Corbie',heure:'14h00',formation:'Doublette',obs:'½J'},
  {date:'2026-10-15',titre:'Feuquières — Vétérans Triplette Qualificatif',type:'veterans',lieu:'Feuquières (Boulodrome)',heure:'9h00',formation:'Triplette',obs:'Limité à 48 éq.'},
  {date:'2026-10-16',titre:'Ault — Vétérans Doublette Mêlée Qualificatif',type:'veterans',lieu:'Ault',heure:'14h00',formation:'Doublette Mêlée',obs:'½J Qualificatif'},
  {date:'2026-10-17',titre:'CHPT DÉPRT — Clubs Open et Féminin (J2)',type:'cdc',lieu:'ASPTT Amiens et Ault/Béthencourt',heure:'',formation:'Open / Féminin'},
  {date:'2026-10-20',titre:'ASPTT Amiens — Vétérans Triplette Mixte',type:'veterans',lieu:'ASPTT Amiens',heure:'14h00',formation:'Triplette Mixte',obs:'½J'},
  {date:'2026-10-22',titre:'Feuquières — Vétérans Triplette Qualificatif',type:'veterans',lieu:'Feuquières (Boulodrome)',heure:'9h00',formation:'Triplette',obs:'Limité à 48 éq.'},
  {date:'2026-10-23',titre:'Ault — Vétérans Doublette Mêlée Qualificatif',type:'veterans',lieu:'Ault',heure:'14h00',formation:'Doublette Mêlée',obs:'½J Qualificatif'},
  {date:'2026-10-24',titre:'Concours Abbeville — Triplette Qualificatif',type:'concours',lieu:'Abbeville',heure:'9h00',formation:'Triplette',obs:'Journée — Jet but 9h'},
  {date:'2026-10-25',titre:'Concours ASPTT Amiens',type:'concours',lieu:'ASPTT Amiens',heure:'14h00',formation:'Doublette',obs:'½J'},
  {date:'2026-10-25',titre:'Concours Feuquières — Triplette Qualificatif',type:'concours',lieu:'Feuquières (Boulodrome)',heure:'9h00',formation:'Triplette',obs:'Journée — 48 éq.'},
  {date:'2026-10-29',titre:'Feuquières — Vétérans Triplette Qualificatif',type:'veterans',lieu:'Feuquières (Boulodrome)',heure:'9h00',formation:'Triplette',obs:'Limité à 48 éq.'},
  {date:'2026-10-30',titre:'Ault — Vétérans Doublette Mêlée Qualificatif',type:'veterans',lieu:'Ault',heure:'14h00',formation:'Doublette Mêlée',obs:'½J Qualificatif'},
  {date:'2026-10-31',titre:'Concours Dargnies',type:'concours',lieu:'Dargnies',heure:'14h00',formation:'Doublette Mixte',obs:'½J'},

  // ══════════════════════════════
  // NOVEMBRE
  // ══════════════════════════════
  {date:'2026-11-01',titre:'Concours Friville',type:'concours',lieu:'Friville',heure:'14h00',formation:'Triplette',obs:'½J'},
  {date:'2026-11-03',titre:'ASPTT Amiens — Vétérans Doublette',type:'veterans',lieu:'ASPTT Amiens',heure:'14h00',formation:'Doublette',obs:'½J'},
  {date:'2026-11-05',titre:'Feuquières — Vétérans Triplette Finale',type:'veterans',lieu:'Feuquières (Boulodrome)',heure:'9h00',formation:'Triplette',obs:'Finale — 24 éq.'},
  {date:'2026-11-06',titre:'Ault — Vétérans Doublette Mêlée Qualificatif',type:'veterans',lieu:'Ault',heure:'14h00',formation:'Doublette Mêlée',obs:'½J Qualificatif'},
  {date:'2026-11-07',titre:'FINALES CHPT DÉPRT — Clubs Open et Féminin',type:'cdc',lieu:'Abbeville',heure:'',formation:'Open / Féminin'},
  {date:'2026-11-10',titre:'Corbie — Vétérans Doublette',type:'veterans',lieu:'Corbie',heure:'14h00',formation:'Doublette',obs:'½J'},
  {date:'2026-11-11',titre:'Concours Gamaches',type:'concours',lieu:'Gamaches',heure:'14h00',formation:'Triplette',obs:'½J'},
  {date:'2026-11-12',titre:'Feuquières — Vétérans Triplette',type:'veterans',lieu:'Feuquières (Boulodrome)',heure:'14h00',formation:'Triplette',obs:'½J'},
  {date:'2026-11-13',titre:'Ault — Vétérans Doublette Mêlée Qualificatif',type:'veterans',lieu:'Ault',heure:'14h00',formation:'Doublette Mêlée',obs:'½J Qualificatif'},
  {date:'2026-11-14',titre:'Concours Abbeville — Triplette Qualificatif',type:'concours',lieu:'Abbeville',heure:'9h00',formation:'Triplette',obs:'Journée — Jet but 9h'},
  {date:'2026-11-14',titre:'Concours ASPTT Amiens — Triplette Qualificatif',type:'concours',lieu:'ASPTT Amiens',heure:'9h00',formation:'Triplette',obs:'Journée — Limité 48 éq.'},
  {date:'2026-11-15',titre:'Concours Feuquières — Triplette Qualificatif',type:'concours',lieu:'Feuquières (Boulodrome)',heure:'9h00',formation:'Triplette',obs:'Journée — 48 éq.'},
  {date:'2026-11-19',titre:'Feuquières — Vétérans Doublette',type:'veterans',lieu:'Feuquières (Boulodrome)',heure:'14h00',formation:'Doublette',obs:'Journée'},
  {date:'2026-11-20',titre:'Ault — Vétérans Doublette Mêlée Qualificatif',type:'veterans',lieu:'Ault',heure:'14h00',formation:'Doublette Mêlée',obs:'½J Qualificatif'},
  {date:'2026-11-21',titre:'ASSEMBLÉE GÉNÉRALE DU COMITÉ',type:'champ',lieu:'Amiens',heure:'10h00',formation:'',obs:'Assemblée générale annuelle'},
  {date:'2026-11-22',titre:'Concours Abbeville — Finale des Qualificatifs',type:'concours',lieu:'Abbeville',heure:'9h00',formation:'Triplette',obs:'Journée — Jet but 9h — Finale'},
  {date:'2026-11-24',titre:'ASPTT Amiens — Vétérans Triplette',type:'veterans',lieu:'ASPTT Amiens',heure:'14h00',formation:'Triplette',obs:'½J'},
  {date:'2026-11-26',titre:'Feuquières — Vétérans Triplette',type:'veterans',lieu:'Feuquières (Boulodrome)',heure:'14h00',formation:'Triplette',obs:'Journée'},
  {date:'2026-11-27',titre:'Ault — Vétérans Doublette Mêlée Qualificatif',type:'veterans',lieu:'Ault',heure:'14h00',formation:'Doublette Mêlée',obs:'½J Qualificatif'},
  {date:'2026-11-28',titre:'Concours ASPTT Amiens — Triplette Qualificatif',type:'concours',lieu:'ASPTT Amiens',heure:'9h00',formation:'Triplette',obs:'Journée — Limité 48 éq.'},
  {date:'2026-11-29',titre:'Concours Feuquières — Triplette Qualificatif',type:'concours',lieu:'Feuquières (Boulodrome)',heure:'9h00',formation:'Triplette',obs:'Journée — 48 éq.'},

  // ══════════════════════════════
  // DÉCEMBRE
  // ══════════════════════════════
  {date:'2026-12-03',titre:'Feuquières — Vétérans Doublette',type:'veterans',lieu:'Feuquières (Boulodrome)',heure:'14h00',formation:'Doublette',obs:'Journée'},
  {date:'2026-12-04',titre:'Ault — Vétérans Doublette Mêlée Finale Qualificatif',type:'veterans',lieu:'Ault',heure:'14h00',formation:'Doublette Mêlée',obs:'½J — Finale Qualificatif'},
  {date:'2026-12-05',titre:'Concours Abbeville',type:'concours',lieu:'Abbeville',heure:'14h00',formation:'Doublette',obs:'½J'},
  {date:'2026-12-05',titre:'Concours ASPTT Amiens — Triplette Qualificatif',type:'concours',lieu:'ASPTT Amiens',heure:'9h00',formation:'Triplette',obs:'Journée — Limité 48 éq.'},
  {date:'2026-12-06',titre:'Concours Feuquières — Triplette Qualificatif',type:'concours',lieu:'Feuquières (Boulodrome)',heure:'9h00',formation:'Triplette',obs:'Journée — 48 éq.'},
  {date:'2026-12-08',titre:'Corbie — Vétérans Doublette',type:'veterans',lieu:'Corbie',heure:'14h00',formation:'Doublette',obs:'½J'},
  {date:'2026-12-10',titre:'Feuquières — Vétérans Triplette',type:'veterans',lieu:'Feuquières (Boulodrome)',heure:'14h00',formation:'Triplette',obs:'Journée'},
  {date:'2026-12-12',titre:'Concours ASPTT Amiens — Triplette Qualificatif',type:'concours',lieu:'ASPTT Amiens',heure:'9h00',formation:'Triplette',obs:'Journée — Limité 48 éq.'},
  {date:'2026-12-13',titre:'Concours Feuquières — Triplette Finale',type:'concours',lieu:'Feuquières (Boulodrome)',heure:'9h00',formation:'Triplette',obs:'Journée — Finale — 24 éq.'},
  {date:'2026-12-15',titre:'ASPTT Amiens — Vétérans Triplette Mixte',type:'veterans',lieu:'ASPTT Amiens',heure:'14h00',formation:'Triplette Mixte',obs:'½J'},
  {date:'2026-12-17',titre:'Feuquières — Vétérans Doublette',type:'veterans',lieu:'Feuquières (Boulodrome)',heure:'14h00',formation:'Doublette',obs:'Journée'},
  {date:'2026-12-19',titre:'Concours ASPTT Amiens — Finale des Qualificatifs',type:'concours',lieu:'ASPTT Amiens',heure:'9h00',formation:'Triplette',obs:'Journée — Finale — Jet but 9h'},

];
